[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read", path = "./node_modules/@jbx-protocol/juice-contracts-v3/deployments/"}] # Get the deployment addresses for forking

[invariant] 
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config